# Generated by Django 5.2 on 2025-04-14 04:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "country_of_origin",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="País de origen"
                    ),
                ),
            ],
            options={
                "verbose_name": "Marca de automóvil",
                "verbose_name_plural": "Marcas de automóviles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CarModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dealer_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID del Concesionario"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SEDAN", "Sedán"),
                            ("SUV", "SUV"),
                            ("WAGON", "Wagon"),
                            ("HATCHBACK", "Hatchback"),
                            ("COUPE", "Coupé"),
                        ],
                        default="SEDAN",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(2015),
                            django.core.validators.MaxValueValidator(2030),
                        ],
                        verbose_name="Año",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Precio",
                    ),
                ),
                (
                    "car_make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="djangoapp.carmake",
                        verbose_name="Marca",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modelo de automóvil",
                "verbose_name_plural": "Modelos de automóviles",
                "ordering": ["car_make__name", "name", "year"],
            },
        ),
    ]
